### ISSUE TITLE
Comos Usuario quiero poder logearme con diferentes métodos para entrar a la aplicación

### ISSUE THREAD

**Issue by ChrisChV** [PauloniaAQP/ScrumTest#1]
## Descripción
El usuario debe poder logearse con su correo, con google o con facebook.
## Tareas
- [ ] Diseño del login #3 
- [ ] Diseño del registrarse #4 
- [ ] Backend de los métodos de autenticación #5
- [ ] Implementación interfaz de login #6
- [ ] Implementación interfaz de registrarse #7
## Criterios de aceptación
- [ ] Crear una cuenta con usuario y contraseña.
- [ ] Crear una cuenta con Facebook.
- [ ] Crear una cuenta con Google.
- [ ] Ingresar con usuario y contraseña.
- [ ] Ingresar con Facebook.
- [ ] Ingresar con Google.
